[[block]]
block = "cpu"
interval = 1
format = " $icon $utilization "

[[block]]
block = "temperature"
interval = 5
format = " $icon CPU: $average "
chip = "k10temp-*"
inputs = ["Tctl"]

[[block]]
block = "memory"
format = " $icon $mem_used_percents "
interval = 5

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
format = " $icon Root: $available / $total "
interval = 20

[[block]]
block = "custom"
command = "~/.config/i3status-rust/scripts/raid-space.sh"
interval = 20

[[block]]
block = "net"
format = " $icon {$signal_strength $ssid|Wired} "
interval = 5

[[block]]
block = "sound"
format = " $icon $volume "

[[block]]
block = "time"
interval = 5
format = " $icon $timestamp.datetime(f:'%Y-%m-%d %H:%M') "

[[block]]
block = "custom"
command = "~/.config/i3status-rust/scripts/gpu.sh"
interval = 5
