[font]
size = 12.0

[font.bold]
family = "IosevkaTerm Nerd Font Propo"
style = "Bold"

[font.bold_italic]
family = "IosevkaTerm Nerd Font Propo"
style = "Bold Italic"

[font.normal]
family = "IosevkaTerm Nerd Font Propo"
style = "Regular"

[window.dimensions]
columns = 90
lines = 30

[window.padding]
x = 5
y = 5

[general]
live_config_reload = true
import = ["~/.config/alacritty/themes/catpuccin_mocha.toml"]
