[font]
size = 10

[font.bold]
family = "IosevkaTerm Nerd Font Propo"
style = "Bold"

[font.bold_italic]
family = "IosevkaTerm Nerd Font Propo"
style = "Bold Italic"

[font.normal]
family = "IosevkaTerm Nerd Font Propo"
style = "Regular"

[window.dimensions]
columns = 90
lines = 30

[window.padding]
x = 4
y = 4

[terminal]
shell = "zsh"

[general]
live_config_reload = true
import = ["~/.config/alacritty/themes/catpuccin_mocha.toml"]
